name: C/C++ CI

on:
  workflow_dispatch:
  #schedule:
  #- cron: "0 22 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
        image: alpine
    
    steps:
      - uses: actions/checkout@v2
        with:
          repository: TinyCC/tinycc
      - name: add alpine testing repository to install tcc
        run: echo "https://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
      - name: add necessary packages
        run: apk add --no-cache tcc musl-dev make
      - name: first stage compile tcc
        run: |
          mkdir -p /first_stage
          ./configure --config-musl --cc=tcc --prefix=/first_stage
          make
          make install
      - name: second stage compile tcc
        run: |
          make clean
          mkdir -p /tcc-binaries
          ./configure --config-musl --cc=/first_stage/bin/tcc --prefix=/tcc-binaries
          make
          make test
          make install
      - name: compress tcc binaries
        run: tar -zcvf tcc-binaries.zip /tcc-binaries
      - name: Get current date-time
        id: datetime
        run: echo "::set-output name=datetime::$(date -u +'%FT%H%MZ')"
      - name: release the binary
        uses: softprops/action-gh-release@v1
        with:
          files: tcc-binaries.zip
          tag_name: ${{ steps.datetime.outputs.datetime }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
