name: C/C++ CI

on:
  workflow_dispatch:
  #schedule:
  #- cron: "0 22 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
        image: alpine
    
    steps:
      - uses: actions/checkout@v2
        with:
          repository: TinyCC/tinycc
      - name: modify repositories
        run: echo "https://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
      - name: add necessary packages, gnu-grep is needed for tcc
        run: apk add --no-cache tcc musl-dev make
      - name: first stage compile tcc
        run: |
          mkdir -p /first_stage
          ./configure --config-musl --cc=tcc --prefix=/first_stage
          make
          make install
      - name: second stage compile tcc
        run: |
          make clean
          mkdir -p /second-stage
          ./configure --config-musl --cc=/first_stage/bin/tcc --prefix=/second-stage
          make
          make test
          make install
