name: C/C++ CI

on:
  workflow_dispatch:
  #schedule:
  #- cron: "0 22 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
        image: alpine
    
    steps:
      - name: Simple test
        run: echo This is the ${GITHUB_WORKSPACE}
      - name: In which OS are we?
        run: uname -a
#       - name: What's in our path?
#         run: |
#           ls -lh /
#           ls -lh /github
      - uses: actions/checkout@v2
        with:
          repository: TinyCC/tinycc
          #path: "/github/workspace"
      - name: Is the repository where expected?
        run: |
          ls -lh ${GITHUB_WORKSPACE}
          echo "Current directory is $PWD"
      - name: modify repositories
        run: echo "https://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
      - name: add necessary packages, gnu-grep is needed for tcc
        run: |
          apk add --no-cache tcc binutils musl-dev make texinfo
          apk add --no-cache --upgrade grep
      - name: first stage compile tcc
        run: |
          #cd /github/workspace/tinycc
          cd ${GITHUB_WORKSPACE}
          mkdir -p /first_stage
          ./configure --config-musl --cc=tcc --prefix=/first_stage
          make
          make install
      - name: second stage compile tcc
        run: |
          make clean
          mkdir -p /second-stage
          ./configure --config-musl --cc=/first_stage/bin/tcc --prefix=/second-stage
          make
          make test
          make install
        
        
#         apk add --no-cache tcc binutils musl-dev make texinfo
#         apk add --no-cache --upgrade grep
#     container:
#       image: frolvlad/alpine-gcc
#       volumes: ${{PWD}}:
#     steps:
#     - name: checkout tinycc repository
#     - uses: actions/checkout@v2
#       with:
#         repository: TinyCC/tinycc
#         #path: my-tools
#     - name: What OS is running
#       run: uname -a
#     - run: cd tinycc
#     - name: configure
#     - run: ./configure --config-musl
#     - name: make
#       run: make
#     - name: make test
#       run: make test
    
#     - name: What java version do we have
#       run: java -version

#     steps:
#     - name: checkout tinycc repository
#     - uses: actions/checkout@v2
#       with:
#         repository: TinyCC/tinycc
#         #path: my-tools
#     - name: install musl-dev
#     - run: sudo apt install musl-dev
#     - run: cd tinycc
#     - name: configure
#     - run: ./configure --config-musl
#     - name: make
#       run: make
#     - name: make test
#       run: make test
#     - name: make distcheck
#       run: make distcheck
